#!/usr/bin/env python3
from pathlib import Path
from PyQt5 import QtCore
from PyQt5.QtWebChannel import QWebChannel
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
from PyQt5.QtWidgets import QApplication, QFileDialog, QGridLayout, QWidget, QShortcut
from PyQt5.QtGui import QKeySequence, QIcon
import sys

app = QApplication(["HTML Viewer"])

icon_path = "img/html-viewer.png"
app.setWindowIcon(QIcon(icon_path))

def open_document(document):
    view.load(QtCore.QUrl('file://'+document))

def open_document_dialog():
    home_dir = str(Path.home())
    file_dialog = QFileDialog()
    file_dialog.setDirectory(home_dir)
    document = file_dialog.getOpenFileName()
    if document[0] != "":
        open_document(document[0])

viewer = QWidget()

layout = QGridLayout()
layout.setContentsMargins(0, 0, 0, 0)
viewer.setLayout(layout)

view = QWebEngineView()
page = QWebEnginePage(view)
channel = QWebChannel()
page.setWebChannel(channel)
view.setPage(page)
shortcut = QShortcut(QKeySequence("Ctrl+O"), view)
shortcut.activated.connect(open_document_dialog)
view.page().setHtml("""
<style>
    body {
        color:white;
        background-color: #252525;
        text-shadow: 2px 2px 5px red
    }
    h1,h2 {
        text-align:center;
    }

    h1 {
        margin-top:10vh;
        font-size:4rem
    }

    h2 {
        margin-top: 22vh
    }

</style>

<h1>HTML Viewer</h1>
<h2>Drag and drop an html/htm/image document to this<br>window to visualize it. Ctrl+O to find it<br>on your device.</h2>
""")

layout.addWidget(view, 0, 0, 1, 1)

viewer.setAcceptDrops(True)
viewer.setGeometry(0, 0, 800, 600)

if len(sys.argv) > 1:
    open_document(sys.argv[1])

viewer.setMinimumSize(400, 500)
viewer.show()

app.exec_()
